-- DROP DATABASE lala;

-- DROP INDEX index_name;

-- ALTER TABLE table_name1
-- TRIGGER index_name;

-- CREATE TABLE TableExample (
--     col10 NUMBER NOT NULL primary key,
--     col11 NUMBER(15,20),
-- );
--
-- CREATE INDEX idx_name
-- ON TableExample(col10, col11);


--
--
-- DELETE FROM CUSTOMERS
-- WHERE ID = 6;
--
-- INSERT INTO Customers (CustomerName, ContactName, Address, City, PostalCode, Country)
-- VALUES ('Cardinal', 'Tom B. Erichsen', 'Skagen 21', 'Stavanger', '4006', 'Norway');

-- CREATE TABLE TableExample (
--     col10 NUMBER NOT NULL primary key,
--     col11 NUMBER(15,20),
--     col12 INT,
--     col13 LONG,
--     col14 REAL,
--     col15 FLOAT(15),
--     col20 VARCHAR(40),
--     col21 CHAR(4),
--     col22 CHARACTER(4),
-- );





SELECT Country, COUNT(CustomerID)
FROM Table1 JOIN Table2 ON Table1.id1=Table2.id2
GROUP BY Country
HAVING COUNT(CustomerID) > 5
ORDER BY COUNT(CustomerID) DESC;

-- SQLGlot Error
-- DROP TABLE authors, titles

-- USE nana
--
-- CREATE UNIQUE INDEX nazov_indexu ON table3 (column1, column2)
--
-- CREATE DATABASE lala;
-- -- CREATE SCHEMA IF NOT EXISTS NovaSchema;
-- CREATE SCHEMA NovaSchema;
-- -- ALTER SCHEMA exe RENAME TO dbo
-- DROP SCHEMA NovaSchema;
--
-- CREATE TABLE table3(
--     id NUMBER NOT NULL PRIMARY KEY);

-- DROP TABLE table3;

-- CREATE TABLE supplier_groups(
--     group_id NUMBER NOT NULL PRIMARY KEY,
--     col2 NUMBER NOT NULL,
--     col3 NUMBER NOT NULL,
--     CONSTRAINT FK_ConstraintTable3 FOREIGN KEY(col2) REFERENCES table3(id));

-- CREATE TABLE suppliers (
--     supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
--     supplier_name VARCHAR2(255) NOT NULL,
--     group_id NUMBER NOT NULL,
--     PRIMARY KEY (supplier_name),
--     UNIQUE (supplier_name),
-- );


-- SELECT COUNT(CustomerID), Country
-- FROM (SELECT Col2 FROM Customers)
-- GROUP BY Country
-- HAVING COUNT(CustomerID) > 5
-- ORDER BY COUNT(CustomerID) DESC;
-- --
-- WITH temporaryTable as
--     (SELECT avg(Attr1)
--     FROM Table)
--     SELECT Attr1
--     FROM Table, temporaryTable
--     WHERE Table.Attr1 > temporaryTable.averageValue;

----------------------------------------------------------------------
---------------------
--  SCHEMA
---------------------

-- CREATE SCHEMA EMP

----------------------------------------------------------------------
---------------------
--  CREATE TABLE
---------------------

-- Bez schemy
-- CREATE TABLE Table1 (
--     ID int NOT NULL PRIMARY KEY,
--     Age INTEGER NOT NULL,
--     LastName varchar(255) NOT NULL Default 'MojDefault',
--     FirstName varchar(255),
--     check (Age>=18 AND FirstName='Joe' OR FirstName='William'),
--     CONSTRAINT FK_ConstraintName FOREIGN KEY(Age) REFERENCES supplier_groups(group_id, col3)
-- );
--
-- DROP TABLE supplier_groups cascade;
-- DROP TABLE supplier_groups;
--
-- -- ----------------------------------------------------------------------

-- ---------------------
-- --  ALTER TABLE
-- ---------------------

-- DROP INDEX index_name;

-- ALTER INDEX distributors RENAME TO suppliers;

-- ALTER TABLE Table1 ADD Email varchar(255);
--
-- ALTER COLUMN BirthDate year;
--
-- ALTER INDEX index_name;

-- CREATE TABLE Table2 (
--           PersonID int NOT NULL PRIMARY KEY,
--           LastName varchar(255) NOT NULL ,
--           FirstName varchar(255),
--           Address varchar(255),
--           City varchar(255)
-- );